[build]
  command = "npm run build"
  publish="build"
  base = "build"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://[mydomain]/*"
  to = "https://[mydomain]/:splat"
  status = 301

  